/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ufc.view;

import br.com.ufc.DAO.EmprestimoDAO;
import br.com.ufc.exception.EJRException;
import br.com.ufc.exception.ENEException;
import br.com.ufc.model.Emprestimo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronny
 */
public class TelaRenovarEmprestimo extends javax.swing.JInternalFrame {
    
    EmprestimoDAO emprestimoDAO = new EmprestimoDAO();

    /**
     * Creates new form TelaRenovarEmprestimo
     */
    public TelaRenovarEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        buscarEmprestimosDoAluno = new javax.swing.JButton();
        renovarEmprestimo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Digite a matrícula do aluno:");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "Livro", "Data de aluguel", "Data de devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        buscarEmprestimosDoAluno.setText("Buscar emprestimos do aluno");
        buscarEmprestimosDoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmprestimosDoAlunoActionPerformed(evt);
            }
        });

        renovarEmprestimo.setText("Renovar");
        renovarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renovarEmprestimoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("ID do emprestimo");

        campoId.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(519, 519, 519))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarEmprestimosDoAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(renovarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarEmprestimosDoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(renovarEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarEmprestimosDoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmprestimosDoAlunoActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) Tabela.getModel();
        while(tabela.getRowCount() > 0)
            tabela.removeRow(0);
        if(campoMatricula.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        else {
            try {
                List<Emprestimo> emprestimos = emprestimoDAO.buscarEmprestimosPorAluno(Integer.parseInt(campoMatricula.getText()));
                for(Emprestimo emprestimo : emprestimos) {
                    int diaA = emprestimo.getAluguel().getDate();
                    int mesA = emprestimo.getAluguel().getMonth() + 1;
                    int anoA = emprestimo.getAluguel().getYear() + 1900;
                    
                    int diaD = emprestimo.getDevolucao().getDate();
                    int mesD = emprestimo.getDevolucao().getMonth() + 1;
                    int anoD = emprestimo.getDevolucao().getYear() + 1900;
                    tabela.addRow(new Object[] { emprestimo.getId(), emprestimo.getAluno().getMatricula(), emprestimo.getLivro().getIsbn(), diaA + "/" + mesA + "/" + anoA, diaD + "/" + mesD + "/" + anoD });
                }
            } catch (ENEException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "O campo matŕicula só aceita números!");
            } finally {
                campoMatricula.setText("");
            }
        }
    }//GEN-LAST:event_buscarEmprestimosDoAlunoActionPerformed

    private void renovarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renovarEmprestimoActionPerformed
        if(campoId.getText().equals(""))
            JOptionPane.showMessageDialog(this, "<html><body>Preencha&nbsp todos&nbsp os&nbsp campos!</body></html>", "ERRO", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                emprestimoDAO.renovarEmprestimo(Integer.parseInt(campoId.getText()));
                JOptionPane.showMessageDialog(this, "<html><body>Empréstimo&nbsp renovado&nbsp com&nbsp sucesso!</body></html>");
            } catch (EJRException | ENEException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "<html><body>O&nbsp campo&nbsp id&nbsp só&nbsp aceita&nbsp números!</body></html>");
            } finally {
                campoId.setText("");
            }
        }
    }//GEN-LAST:event_renovarEmprestimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton buscarEmprestimosDoAluno;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton renovarEmprestimo;
    // End of variables declaration//GEN-END:variables
}
