/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ufc.view;

import br.com.ufc.util.PosicaoFormulario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.ImageIcon;

/**
 *
 * @author ronny
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    JInternalFrame frameAberto = new JInternalFrame();
    
    PosicaoFormulario form = new PosicaoFormulario();
    TelaExcluirLivro tel;
    TelaCadastroAluno tca;
    TelaExcluirAluno tea;
    TelaVizualizarAluno tva;
    TelaCadastroLivro tcl;
    TelaVizualizarLivro tvl;
    TelaEmprestarLivro teml;
    TelaDevolverLivro tdl;
    TelaVizualizarEmprestimo tve;
    /**
     * Creates new form SistemaBiblioteca
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        ImageIcon imagem = new ImageIcon("/home/ronny/NetBeansProjects/Biblioteca/Biblioteca/src/imagens/library-enter6.jpg");
        menuPrincipal.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height-50);
        System.out.println(menuPrincipal.getWidth() + "/" + menuPrincipal.getHeight());
        menuPrincipal.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height-50, Image.SCALE_DEFAULT)));
    }
    
    public void openFrame(JInternalFrame frame) {
        form.abrirFormulario(frame, menuPrincipal);
        frameAberto.hide();
        frameAberto = frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrarAluno = new javax.swing.JMenuItem();
        excluirAluno = new javax.swing.JMenuItem();
        vizualizarAluno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadastrarLivro = new javax.swing.JMenuItem();
        excluirLivro = new javax.swing.JMenuItem();
        vizualizarLivro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        emprestarLivro = new javax.swing.JMenuItem();
        devolverLivro = new javax.swing.JMenuItem();
        vizualizarEmprestimos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Aluno");
        jMenu1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        cadastrarAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cadastrarAluno.setText("Cadastrar");
        cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarAluno);

        excluirAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        excluirAluno.setText("Excluir");
        excluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(excluirAluno);

        vizualizarAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        vizualizarAluno.setText("Vizualizar");
        vizualizarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizarAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(vizualizarAluno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Livro");
        jMenu2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        cadastrarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cadastrarLivro.setText("Cadastrar");
        cadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLivroActionPerformed(evt);
            }
        });
        jMenu2.add(cadastrarLivro);

        excluirLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        excluirLivro.setText("Excluir");
        excluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirLivroActionPerformed(evt);
            }
        });
        jMenu2.add(excluirLivro);

        vizualizarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        vizualizarLivro.setText("Vizualizar");
        vizualizarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizarLivroActionPerformed(evt);
            }
        });
        jMenu2.add(vizualizarLivro);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empréstimo");
        jMenu3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        emprestarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        emprestarLivro.setText("Emprestar livro");
        emprestarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestarLivroActionPerformed(evt);
            }
        });
        jMenu3.add(emprestarLivro);

        devolverLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        devolverLivro.setText("Devolver livro");
        devolverLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverLivroActionPerformed(evt);
            }
        });
        jMenu3.add(devolverLivro);

        vizualizarEmprestimos.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        vizualizarEmprestimos.setText("Vizualizar emprestimos");
        vizualizarEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizarEmprestimosActionPerformed(evt);
            }
        });
        jMenu3.add(vizualizarEmprestimos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirLivroActionPerformed
        tel = new TelaExcluirLivro();
        openFrame(tel);
    }//GEN-LAST:event_excluirLivroActionPerformed

    private void cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoActionPerformed
        tca = new TelaCadastroAluno();
        openFrame(tca);
    }//GEN-LAST:event_cadastrarAlunoActionPerformed

    private void excluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAlunoActionPerformed
        tea = new TelaExcluirAluno();
        openFrame(tea);
    }//GEN-LAST:event_excluirAlunoActionPerformed

    private void vizualizarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarAlunoActionPerformed
        tva = new TelaVizualizarAluno();
        openFrame(tva);
    }//GEN-LAST:event_vizualizarAlunoActionPerformed

    private void cadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLivroActionPerformed
        tcl = new TelaCadastroLivro();
        openFrame(tcl);
    }//GEN-LAST:event_cadastrarLivroActionPerformed

    private void vizualizarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarLivroActionPerformed
        tvl = new TelaVizualizarLivro();
        openFrame(tvl);
    }//GEN-LAST:event_vizualizarLivroActionPerformed

    private void emprestarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestarLivroActionPerformed
        teml = new TelaEmprestarLivro();
        openFrame(teml);
    }//GEN-LAST:event_emprestarLivroActionPerformed

    private void devolverLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLivroActionPerformed
        tdl = new TelaDevolverLivro();
        openFrame(tdl);
    }//GEN-LAST:event_devolverLivroActionPerformed

    private void vizualizarEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarEmprestimosActionPerformed
        tve = new TelaVizualizarEmprestimo();
        openFrame(tve);
    }//GEN-LAST:event_vizualizarEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarAluno;
    private javax.swing.JMenuItem cadastrarLivro;
    private javax.swing.JMenuItem devolverLivro;
    private javax.swing.JMenuItem emprestarLivro;
    private javax.swing.JMenuItem excluirAluno;
    private javax.swing.JMenuItem excluirLivro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel menuPrincipal;
    private javax.swing.JMenuItem vizualizarAluno;
    private javax.swing.JMenuItem vizualizarEmprestimos;
    private javax.swing.JMenuItem vizualizarLivro;
    // End of variables declaration//GEN-END:variables
}
